
models:
  - model: w2v2_6_3
    equivalence: phoneme

  - model: w2v2_6_8
    equivalence: phoneme
  - model: w2v2_6_8
    equivalence: syllable
  - model: w2v2_6_8
    equivalence: next_phoneme
  - model: w2v2_6_8
    equivalence: phoneme_within_word_prefix
  - model: w2v2_6_8
    equivalence: phoneme_within_word_suffix
  - model: w2v2_6_8
    equivalence: word

  - model: w2v2_6_32
    equivalence: phoneme_within_word_prefix
  - model: w2v2_6_32
    equivalence: phoneme_within_word_suffix

  # random LSTM models
  - model: random_w2v2_6_8
    equivalence: random
  - model: random_w2v2_6_32
    equivalence: random

  # random feedforward models
  - model: randomff_w2v2_6_8
    equivalence: random
  - model: randomff_w2v2_6_32
    equivalence: random

encoding:
  data:
    - subject: EC152
      blocks:
        - B22

    - subject: EC196
      blocks:
        - B1

    - subject: EC195
      blocks:
        - B1

    - subject: EC183
      blocks:
        - B43

    - subject: EC212
      blocks:
        - B13

  model_comparisons:
    - model2: phoneme
      model1: baseline
    - model2: phoneme8
      model1: baseline
    - model2: next_phoneme
      model1: baseline
    - model2: syllable
      model1: baseline
    - model2: random8
      model1: baseline