datasets:
  timit:
    raw_path: data/timit_raw


models:
  - base_model: w2v2_6
    dataset: timit
    model: rnn_3-weightdecay0.01
    equivalence: phoneme_10frames

  # - base_model: w2v2_6
  #   dataset: timit
  #   model: rnn_8-weightdecay0.01
  #   equivalence: phoneme_10frames
  - base_model: w2v2_6
    dataset: timit
    model: rnn_8-weightdecay0.01
    equivalence: syllable_10frames
  - base_model: w2v2_6
    dataset: timit
    model: rnn_3-weightdecay0.01
    equivalence: next_phoneme_10frames
  # - base_model: w2v2_6
  #   dataset: timit
  #   model: rnn_8-weightdecay0.01
  #   equivalence: phoneme_within_word_prefix
  # - base_model: w2v2_6
  #   dataset: timit
  #   model: rnn_8-weightdecay0.01
  #   equivalence: phoneme_within_word_suffix
  - base_model: w2v2_6
    dataset: timit
    model: rnn_8-weightdecay0.01
    equivalence: word_10frames
  - base_model: w2v2_6
    dataset: timit
    model: rnn_8-weightdecay0.01
    equivalence: word_broad_10frames
  - base_model: w2v2_6
    dataset: timit
    model: rnn_8-weightdecay0.01
    equivalence: biphone_recon_10frames
  - base_model: w2v2_6
    dataset: timit
    model: rnn_8-weightdecay0.01
    equivalence: biphone_pred_10frames

  # - base_model: w2v2_6
  #   model: rnn_32
  #   equivalence: phoneme_within_word_prefix
  # - base_model: w2v2_6
  #   model: rnn_32
  #   equivalence: phoneme_within_word_suffix

  # random LSTM models
  - base_model: w2v2_6
    dataset: timit
    model: randomrnn_8
    equivalence: random
  - base_model: w2v2_6
    dataset: timit
    model: randomrnn_32
    equivalence: random

  # random feedforward models
  - base_model: w2v2_6
    dataset: timit
    model: randomff_8
    equivalence: random
  - base_model: w2v2_6
    dataset: timit
    model: randomff_32
    equivalence: random

encoding:
  data:
    - subject: EC152
      blocks:
        - B22

    - subject: EC196
      blocks:
        - B1

    - subject: EC195
      blocks:
        - B1

    - subject: EC183
      blocks:
        - B43

    - subject: EC212
      blocks:
        - B13

  model_comparisons:
    - model2: phoneme
      model1: baseline
    - model2: phoneme8
      model1: baseline
    - model2: next_phoneme
      model1: baseline
    - model2: syllable
      model1: baseline
    - model2: random8
      model1: baseline


synthetic_encoding:

  evaluations:

    basic10:
      num_components: 10
      num_embeddings_to_select: 3

      models:
        - phoneme
        - biphone_recon
        - syllable
        - word_broad

    basic50:
      num_components: 50
      num_embeddings_to_select: 3

      models:
        - phoneme
        - biphone_recon
        - syllable
        - word_broad