_target_: src.datasets.speech_equivalence.make_timit_equivalence_dataset

# dummy; this should not be used; just makes pipelining easier
name: random
equivalence_classer: phoneme
num_frames_per_phoneme: 1